<a href="https://colab.research.google.com/github/Abdul8189/datascience/blob/main/Imbalencing_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
dataset=pd.read_csv('ads.csv')

In [ ]:
dataset.head(10)

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0
5   27            58000          0
6   27            84000          0
7   32           150000          1
8   25            33000          0
9   35            65000          0

In [ ]:
dataset['Purchased'].value_counts()

Purchased
0    257
1    143
Name: count, dtype: int64

In [ ]:
x= dataset.iloc[:,:-1]

In [ ]:
y= dataset['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr=LogisticRegression()

In [ ]:
lr.fit(x_train,y_train)

LogisticRegression()

In [ ]:
lr.score(x_test,y_test)

0.8875

In [ ]:
lr.predict([[46,	26000	]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
from imblearn.under_sampling import  RandomUnderSampler

In [ ]:
rm=RandomUnderSampler()

In [ ]:
rm.fit(x,y)

RandomUnderSampler()

In [ ]:
rm.fit_resample(x,y)

(     Age  EstimatedSalary
 135   23            63000
 309   38            50000
 93    29            28000
 46    25            79000
 50    24            32000
 ..   ...              ...
 393   60            42000
 395   46            41000
 396   51            23000
 397   50            20000
 399   49            36000
 
 [286 rows x 2 columns],
 135    0
 309    0
 93     0
 46     0
 50     0
       ..
 393    1
 395    1
 396    1
 397    1
 399    1
 Name: Purchased, Length: 286, dtype: int64)

In [ ]:
ru_x,ru_y=rm.fit_resample(x,y)

In [ ]:
ru_x

Age  EstimatedSalary
76    18            52000
333   40            65000
338   38            55000
144   34            25000
246   35            50000
..   ...              ...
393   60            42000
395   46            41000
396   51            23000
397   50            20000
399   49            36000

[286 rows x 2 columns]

In [ ]:
ru_y

76     0
333    0
338    0
144    0
246    0
      ..
393    1
395    1
396    1
397    1
399    1
Name: Purchased, Length: 286, dtype: int64

In [ ]:
ru_x.value_counts()

Age  EstimatedSalary
34   43000              2
35   50000              2
41   52000              2
60   42000              2
38   50000              2
                       ..
35   38000              1
     25000              1
     22000              1
     20000              1
     60000              1
Name: count, Length: 270, dtype: int64

In [ ]:
ru_y.value_counts()

Purchased
0    143
1    143
Name: count, dtype: int64

In [ ]:
x1_train,x1_test,y1_train,y1_test=train_test_split(ru_x,ru_y,test_size=0.2)

In [ ]:
lr1=LogisticRegression()

In [ ]:
lr1.fit(x1_train,y1_train)

LogisticRegression()

In [ ]:
lr1.predict([[45,35000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])

In [ ]:
lr1.score(x1_test,y1_test)

0.8620689655172413

In [ ]:
from imblearn.over_sampling import RandomOverSampler

In [ ]:
ro=RandomOverSampler()

In [ ]:
ro.fit_resample(x,y)

(     Age  EstimatedSalary
 0     19            19000
 1     35            20000
 2     26            43000
 3     27            57000
 4     19            76000
 ..   ...              ...
 509   52            90000
 510   36           125000
 511   39           122000
 512   36           144000
 513   42           104000
 
 [514 rows x 2 columns],
 0      0
 1      0
 2      0
 3      0
 4      0
       ..
 509    1
 510    1
 511    1
 512    1
 513    1
 Name: Purchased, Length: 514, dtype: int64)

In [ ]:
xd1,yd1=ro.fit_resample(x,y)

In [ ]:
xd1.value_counts()

Age  EstimatedSalary
39   134000             6
47   25000              6
45   22000              5
60   42000              4
45   131000             4
                       ..
57   122000             1
58   23000              1
     38000              1
19   85000              1
     76000              1
Name: count, Length: 365, dtype: int64

In [ ]:
yd1.value_counts()

Purchased
0    257
1    257
Name: count, dtype: int64

In [ ]:
x2_train,x2_test,y2_train,y2_test=train_test_split(xd1,yd1,test_size=0.2)

In [ ]:
lr2=LogisticRegression()

In [ ]:
lr2.fit(x2_train,y2_train)

LogisticRegression()

In [ ]:
lr2.score(x2_test,y2_test)

0.8446601941747572

In [ ]:
lr2.predict([[45,26000]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0])